import Head from "next/head";
import Layout from "@/components/Layout";
import Image from "next/image";
import hockeyPlayer from "../public/images/landingPage/hockey-player-1.png";
import proudMember from "../public/images/landingPage/proud-members.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Gateway Ice Center</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex flex-col items-center text-dark  w-full min-h-screen ">
        <Layout className="w-full min-h-screen flex flex-col items-center justify-between bg-gradient-to-b from-glossy to-light">
          <div className="flex flex-col items-center gap-5 -mt-20">
            <div>
              <h1 className="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gatewayBlue md:text-5xl lg:text-6xl dark:text-white">
                Welcome to Gateway Ice Center
              </h1>
            </div>
            <div className="px-10">
              <p className="my-4 text-lg leading-7 font-semibold">
                Since 1995, we have been the premier provider of ice skating
                experiences for families and individuals througout the Fresno
                Community and beyond. We offer public ice skating, skating
                lessons, birthday parties, youth hockey, adult hockey,
                broomball, figure skating, private rentals, special events,
                holiday shows, competitions, competitive skating and much more.
                All under one roof! We are proud to be a member of USA Hockey,
                US Figure Skating and USIRA (US Ice Rink Association)
              </p>
            </div>
          </div>
          <div className="flex w-full">
            <div className="w-1/3">
              {/* <Image
                src={figureSkater}
                alt="athletes"
                className="w-full h-auto rounded-md"
              ></Image> */}
              <Image
                src={hockeyPlayer}
                alt="athletes"
                className="w-full h-auto"
              ></Image>
            </div>

            <div className="w-2/3 h-auto flex flex-col justify-evenly">
              <div className="mb-10">
                <Image
                  src={proudMember}
                  alt="proudMember"
                  className="w-full h-auto"
                ></Image>
              </div>

              <div className="flex flex-col self-center">
                <AnimatedText
                  text="Turn Your Dreams into Reality!"
                  className="!text-5xl !text-left text-gatewayBlue"
                />
                <p className="my-4 text-base font-medium">
                  At Gateway Ice Center passion becomes skill, and friends
                  become family!
                </p>
                <div className="flex items-center self-start mt-2 w-full">
                  <Link
                    href="/dummy.pdf"
                    target={"_blank"}
                    className="flex items-center text-center bg-glossy text-dark p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                    download={true}
                  >
                    Download Our Calendar
                    <LinkArrow className={"ml-2"} />
                  </Link>
                  <Link
                    href="mailto:abcd@gmail.com"
                    target={"_blank"}
                    className="ml-4 text-lg font-medium capitalize text-dark underline"
                  >
                    Contact Us
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </Layout>
        {/* <Footer /> */}
      </main>
    </>
  );
}
